'use client';
import { FormEvent,useEffect,useMemo,useState } from 'react';
import { Boxes,ChevronDown,LayoutDashboard,LogOut,Plus,RefreshCw,Search,ShoppingBag,Tags,Upload,X } from 'lucide-react';
import { assetUrl,isSupabaseConfigured,sitePath,supabase,whatsappUrl } from '../../lib/supabase';
import './admin.css';

type Tab='dashboard'|'products'|'showcase'|'categories'|'orders';
type Category={id:string;name:string;slug:string;sort_order:number;is_active:boolean};
type Product={id:string;slug:string;name:string;category_id:string|null;price:number;old_price:number|null;stock:number;low_stock_threshold:number;weight:string;flavor:string|null;description:string;badge:string|null;image_url:string;gallery_urls:string[];featured_order:number|null;is_active:boolean;deleted_at:string|null;categories?:{name:string}|null};
type Order={id:string;order_number:string;customer_name:string|null;customer_phone:string;customer_email:string|null;delivery_method:string|null;delivery_address:string|null;comment:string|null;manager_note:string|null;tracking_number:string|null;status:string;total:number;created_at:string;order_items?:Array<{id:string;product_name:string;product_weight:string;quantity:number;unit_price:number}>};
const statusLabels:Record<string,string>={new:'Новый',confirmed:'Подтверждён',processing:'В сборке',shipped:'Отправлен',completed:'Завершён',cancelled:'Отменён'};
const money=(n:number)=>`${Number(n).toLocaleString('ru-RU')} ₽`;

export default function Admin(){
 const [ready,setReady]=useState(false),[tab,setTab]=useState<Tab>('dashboard'),[products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[orders,setOrders]=useState<Order[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[editing,setEditing]=useState<Product|null|undefined>(undefined),[message,setMessage]=useState('');
 const load=async()=>{if(!supabase)return;const [{data:p},{data:c},{data:o}]=await Promise.all([supabase.from('products').select('*,categories(name)').is('deleted_at',null).order('sort_order'),supabase.from('categories').select('*').order('sort_order'),supabase.from('orders').select('*,order_items(*)').order('created_at',{ascending:false}).limit(100)]);setProducts((p||[]) as Product[]);setCategories((c||[]) as Category[]);setOrders((o||[]) as Order[])};
 useEffect(()=>{if(!isSupabaseConfigured){setReady(true);return}supabase!.auth.getSession().then(async({data})=>{if(!data.session){location.href=sitePath('/admin/login');return}const role=data.session.user.app_metadata?.role;if(role!=='admin'){await supabase!.auth.signOut();location.href=sitePath('/admin/login');return}await load();setReady(true)});const channel=supabase!.channel('admin-orders').on('postgres_changes',{event:'*',schema:'public',table:'orders'},()=>load()).subscribe();return()=>{void supabase!.removeChannel(channel)}},[]);
 const logout=async()=>{await supabase?.auth.signOut();location.href=sitePath('/admin/login')};
 const filteredProducts=useMemo(()=>products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())),[products,query]);
 const filteredOrders=useMemo(()=>orders.filter(o=>(status==='all'||o.status===status)&&(o.order_number+o.customer_phone+(o.customer_name||'')).toLowerCase().includes(query.toLowerCase())),[orders,status,query]);
 if(!ready)return <main className="admin-loading"><RefreshCw className="spin"/> Загружаем админку…</main>;
 if(!isSupabaseConfigured)return <main className="admin-loading"><div><h1>АДМИНКА ПОДГОТОВЛЕНА</h1><p>Для входа добавьте переменные Supabase и примените SQL-файлы из папки <code>supabase</code>.</p><a href={sitePath('/')}>Вернуться в магазин</a></div></main>;
 const nav=[['dashboard','Обзор',LayoutDashboard],['products','Товары',Boxes],['showcase','Витрина',ShoppingBag],['categories','Категории',Tags],['orders','Заказы',ShoppingBag]] as const;
 return <main className="admin-shell"><aside className="admin-sidebar"><img src={assetUrl('/brand/no-limits-light.png')} alt="NO LIMITS"/>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setQuery('')}}><Icon/>{label}</button>)}<button className="logout" onClick={logout}><LogOut/>Выйти</button></aside><section className="admin-content"><header><div><p>NO LIMITS / УПРАВЛЕНИЕ</p><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><button className="refresh" onClick={load}><RefreshCw/> Обновить</button></header>{message&&<div className="admin-message">{message}<button onClick={()=>setMessage('')}><X/></button></div>}
 {tab==='dashboard'&&<Dashboard products={products} orders={orders}/>} 
 {tab==='products'&&<><div className="admin-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Найти товар"/></label><button className="primary" onClick={()=>setEditing(null)}><Plus/> Добавить товар</button></div><div className="admin-table-wrap"><table><thead><tr><th>Товар</th><th>Категория</th><th>Цена</th><th>Остаток</th><th>Видимость</th><th/></tr></thead><tbody>{filteredProducts.map(p=><tr key={p.id}><td><div className="product-cell"><img src={assetUrl(p.image_url||'/favicon.png')} alt=""/><div><strong>{p.name}</strong><small>{p.weight}</small></div></div></td><td>{p.categories?.name||'—'}</td><td>{money(p.price)}</td><td><StockInput product={p} saved={load}/></td><td><Toggle checked={p.is_active} onChange={async v=>{await supabase!.from('products').update({is_active:v}).eq('id',p.id);load()}}/></td><td><button className="text-btn" onClick={()=>setEditing(p)}>Изменить</button></td></tr>)}</tbody></table></div>{editing!==undefined&&<ProductModal product={editing} categories={categories} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);setMessage('Товар сохранён');load()}}/>}</>}
 {tab==='showcase'&&<Showcase products={products} saved={()=>{setMessage('Витрина обновлена');load()}}/>}
 {tab==='categories'&&<Categories categories={categories} saved={load}/>} 
 {tab==='orders'&&<><div className="admin-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Номер, имя или телефон"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Все статусы</option>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="orders-list">{filteredOrders.map(o=><OrderCard key={o.id} order={o} saved={load}/>)}</div></>}
 </section></main>
}

function Dashboard({products,orders}:{products:Product[];orders:Order[]}){const today=new Date().toDateString();const todayOrders=orders.filter(o=>new Date(o.created_at).toDateString()===today);const active=orders.filter(o=>!['completed','cancelled'].includes(o.status));const revenue=orders.filter(o=>o.status==='completed').reduce((s,o)=>s+Number(o.total),0);const low=products.filter(p=>p.stock<=p.low_stock_threshold);return <><div className="stat-grid"><Stat label="Заявок сегодня" value={todayOrders.length}/><Stat label="Активных заказов" value={active.length}/><Stat label="Выручка" value={money(revenue)}/><Stat label="Мало на складе" value={low.length}/></div><div className="dash-grid"><div className="panel"><h2>Последние заказы</h2>{orders.slice(0,6).map(o=><div className="row" key={o.id}><strong>{o.order_number}</strong><span>{o.customer_name||o.customer_phone}</span><b>{money(o.total)}</b></div>)}</div><div className="panel"><h2>Низкие остатки</h2>{low.length?low.slice(0,8).map(p=><div className="row" key={p.id}><strong>{p.name}</strong><b className="danger">{p.stock} шт.</b></div>):<p className="muted">Все остатки в норме.</p>}</div></div></>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
function Toggle({checked,onChange}:{checked:boolean;onChange:(v:boolean)=>void}){return <button aria-label="Переключить" className={`toggle ${checked?'on':''}`} onClick={()=>onChange(!checked)}><i/></button>}
function StockInput({product,saved}:{product:Product;saved:()=>void}){const [v,setV]=useState(product.stock);return <input className={v<=product.low_stock_threshold?'stock-low':'stock-input'} type="number" min="0" value={v} onChange={e=>setV(Number(e.target.value))} onBlur={async()=>{if(v!==product.stock){await supabase!.from('products').update({stock:v}).eq('id',product.id);saved()}}}/>}

function Showcase({products,saved}:{products:Product[];saved:()=>void}){
 const initial=()=>Array.from({length:4},(_,i)=>products.find(p=>p.featured_order===i+1)?.id||'');
 const [slots,setSlots]=useState<string[]>(initial),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>setSlots(initial()),[products]);
 const save=async()=>{setError('');const selected=slots.filter(Boolean);if(new Set(selected).size!==selected.length){setError('Выберите разные товары для каждого места.');return}setBusy(true);const changed=products.filter(p=>(p.featured_order||null)!==(slots.indexOf(p.id)>=0?slots.indexOf(p.id)+1:null));for(const p of changed){const position=slots.indexOf(p.id);const {error:saveError}=await supabase!.from('products').update({featured_order:position>=0?position+1:null}).eq('id',p.id);if(saveError){setError(saveError.message);setBusy(false);return}}setBusy(false);saved()};
 return <div className="panel showcase-panel"><h2>Товары на первом экране</h2><p className="muted">Выберите до четырёх позиций. Они появятся в карусели в указанном порядке.</p><div className="showcase-grid">{slots.map((id,i)=><label key={i}><span>Позиция {i+1}</span><select value={id} onChange={e=>setSlots(v=>v.map((x,j)=>j===i?e.target.value:x))}><option value="">Автоматически</option>{products.filter(p=>p.is_active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{id&&<img src={assetUrl(products.find(p=>p.id===id)?.image_url||'/favicon.svg')} alt=""/>}</label>)}</div>{error&&<p className="admin-error" role="alert">{error}</p>}<button className="primary" onClick={save} disabled={busy}>{busy?'Сохраняем…':'Сохранить витрину'}</button></div>
}
function ProductModal({product,categories,close,saved}:{product:Product|null;categories:Category[];close:()=>void;saved:()=>void}){
 const [busy,setBusy]=useState(false),[image,setImage]=useState(product?.image_url||''),[gallery,setGallery]=useState<string[]>(product?.gallery_urls||[]),[error,setError]=useState('');
 const upload=async(file:File)=>{const path=`${Date.now()}-${Math.random().toString(36).slice(2,8)}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const {error:uploadError}=await supabase!.storage.from('product-images').upload(path,file,{contentType:file.type});if(uploadError)throw uploadError;return supabase!.storage.from('product-images').getPublicUrl(path).data.publicUrl};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');try{const fd=new FormData(e.currentTarget);let image_url=image.trim();const files=Array.from((fd.getAll('image_files') as File[]).filter(f=>f?.size));const uploaded=await Promise.all(files.map(upload));if(!image_url&&uploaded.length)image_url=uploaded.shift()!;const gallery_urls=[...gallery,...uploaded];if(!image_url)throw new Error('Добавьте основное фото товара.');const payload={name:String(fd.get('name')).trim(),slug:String(fd.get('slug')).trim(),category_id:String(fd.get('category_id'))||null,price:Number(fd.get('price')),old_price:fd.get('old_price')?Number(fd.get('old_price')):null,stock:Number(fd.get('stock')),low_stock_threshold:Number(fd.get('low_stock_threshold')),weight:String(fd.get('weight')),flavor:String(fd.get('flavor'))||null,description:String(fd.get('description')),badge:String(fd.get('badge'))||null,image_url,gallery_urls,is_active:fd.get('is_active')==='on'};const result=product?await supabase!.from('products').update(payload).eq('id',product.id):await supabase!.from('products').insert(payload);if(result.error)throw result.error;saved()}catch(err){setError(err instanceof Error?err.message:'Не удалось сохранить товар.')}finally{setBusy(false)}};
 const remove=async()=>{if(!product||!confirm('Скрыть этот товар из каталога?'))return;const {error:removeError}=await supabase!.from('products').update({is_active:false,deleted_at:new Date().toISOString()}).eq('id',product.id);if(removeError)setError(removeError.message);else saved()};
 return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><header><h2>{product?'Изменить товар':'Новый товар'}</h2><button type="button" onClick={close}><X/></button></header><div className="form-grid"><label>Название<input name="name" defaultValue={product?.name} required/></label><label>Slug<input name="slug" defaultValue={product?.slug} required/></label><label>Категория<select name="category_id" defaultValue={product?.category_id||''} required><option value="">Выберите</option>{categories.filter(c=>c.is_active||c.id===product?.category_id).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Вес / объём<input name="weight" defaultValue={product?.weight}/></label><label>Цена<input name="price" type="number" min="0" defaultValue={product?.price} required/></label><label>Старая цена<input name="old_price" type="number" min="0" defaultValue={product?.old_price||''}/></label><label>Остаток<input name="stock" type="number" min="0" defaultValue={product?.stock||0} required/></label><label>Порог «мало»<input name="low_stock_threshold" type="number" min="0" defaultValue={product?.low_stock_threshold??5}/></label><label>Вкус<input name="flavor" defaultValue={product?.flavor||''}/></label><label>Бейдж<input name="badge" defaultValue={product?.badge||''} placeholder="ХИТ"/></label><label className="wide">Описание<textarea name="description" defaultValue={product?.description}/></label><label className="wide">Основное фото — ссылка<input value={image} onChange={e=>setImage(e.target.value)} placeholder="https://… или /products/…"/></label><label className="upload wide"><Upload/> Загрузить фото (можно выбрать сразу несколько)<input name="image_files" type="file" accept="image/*" multiple/></label><div className="wide"><p>Дополнительные фото: {gallery.length}. Можно добавить 3 и больше.</p><div className="admin-gallery">{gallery.map((url,i)=><div key={url+i}><img src={assetUrl(url)} alt={`Фото ${i+2}`}/><button type="button" onClick={()=>setGallery(v=>v.filter((_,j)=>j!==i))} aria-label={`Удалить фото ${i+2}`}><X size={16}/></button></div>)}</div></div><label className="check wide"><input name="is_active" type="checkbox" defaultChecked={product?.is_active??true}/> Показывать на сайте</label></div>{error&&<p className="admin-error" role="alert">{error}</p>}<footer><button type="button" className="danger-btn" onClick={remove} disabled={!product||busy}>Удалить</button><button className="primary" disabled={busy}>{busy?'Сохраняем…':'Сохранить'}</button></footer></form></div>
}

function Categories({categories,saved}:{categories:Category[];saved:()=>void}){const add=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);await supabase!.from('categories').insert({name:String(fd.get('name')),slug:String(fd.get('slug')),sort_order:categories.length*10+10});e.currentTarget.reset();saved()};return <div className="dash-grid"><form className="panel category-form" onSubmit={add}><h2>Новая категория</h2><input name="name" placeholder="Название" required/><input name="slug" placeholder="slug" required/><button className="primary">Добавить</button></form><div className="panel"><h2>Категории</h2>{categories.map(c=><div className="row" key={c.id}><div><strong>{c.name}</strong><small> /{c.slug}</small></div><Toggle checked={c.is_active} onChange={async v=>{await supabase!.from('categories').update({is_active:v}).eq('id',c.id);saved()}}/></div>)}</div></div>}

function OrderCard({order,saved}:{order:Order;saved:()=>void}){const [open,setOpen]=useState(false),[busy,setBusy]=useState(false);const change=async(v:string)=>{setBusy(true);const {error}=await supabase!.rpc('change_order_status',{p_order_id:order.id,p_status:v});if(error)alert(error.message.includes('INSUFFICIENT_STOCK')?'Недостаточно товара на складе.':error.message);setBusy(false);saved()};return <article className="order-card"><button className="order-summary" onClick={()=>setOpen(v=>!v)}><div><strong>{order.order_number}</strong><span>{new Date(order.created_at).toLocaleString('ru-RU')}</span></div><div><span>{order.customer_name||'Без имени'}</span><b>{order.customer_phone}</b></div><strong>{money(order.total)}</strong><span className={`status status-${order.status}`}>{statusLabels[order.status]}</span><ChevronDown className={open?'flip':''}/></button>{open&&<div className="order-details"><div><h3>Состав</h3>{order.order_items?.map(i=><p key={i.id}>{i.product_name} · {i.quantity} шт. — {money(i.unit_price*i.quantity)}</p>)}</div><div><h3>Клиент и доставка</h3><p>{order.customer_email||'Email не указан'}</p><p>{order.delivery_method||'Способ не указан'} · {order.delivery_address||'Адрес уточнит менеджер'}</p><p>{order.comment||'Без комментария'}</p>{whatsappUrl&&<a href={`${whatsappUrl}?text=${encodeURIComponent(`Здравствуйте! По заказу ${order.order_number}`)}`} target="_blank">Написать в WhatsApp</a>}</div><div className="order-actions"><label>Статус<select value={order.status} disabled={busy} onChange={e=>change(e.target.value)}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Трек-номер<input defaultValue={order.tracking_number||''} onBlur={async e=>{await supabase!.from('orders').update({tracking_number:e.target.value}).eq('id',order.id)}}/></label><label className="wide">Заметка менеджера<textarea defaultValue={order.manager_note||''} onBlur={async e=>{await supabase!.from('orders').update({manager_note:e.target.value}).eq('id',order.id)}}/></label></div></div>}</article>}
